exports.deployConract = require("./check-nft")
exports.deployConract = require("./check-wnft")
exports.deployConract = require("./mint-nft")
exports.deployConract = require("./lock-cross")
exports.deployConract = require("./burn-cross")